// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
#include "CANTalon.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<CANTalon> RobotMap::driveSubCANTalon1;
std::shared_ptr<CANTalon> RobotMap::driveSubCANTalon2;
std::shared_ptr<CANTalon> RobotMap::driveSubCANTalon3;
std::shared_ptr<CANTalon> RobotMap::driveSubCANTalon4;
std::shared_ptr<RobotDrive> RobotMap::driveSubRobotDrive41;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    driveSubCANTalon1.reset(new CANTalon(1));
    lw->AddActuator("DriveSub", "CAN Talon 1", driveSubCANTalon1);
    
    driveSubCANTalon2.reset(new CANTalon(2));
    lw->AddActuator("DriveSub", "CAN Talon 2", driveSubCANTalon2);
    
    driveSubCANTalon3.reset(new CANTalon(3));
    lw->AddActuator("DriveSub", "CAN Talon 3", driveSubCANTalon3);
    
    driveSubCANTalon4.reset(new CANTalon(4));
    lw->AddActuator("DriveSub", "CAN Talon 4", driveSubCANTalon4);
    
    driveSubRobotDrive41.reset(new RobotDrive(driveSubCANTalon1, driveSubCANTalon2,
              driveSubCANTalon3, driveSubCANTalon4));
    
    driveSubRobotDrive41->SetSafetyEnabled(true);
        driveSubRobotDrive41->SetExpiration(0.1);
        driveSubRobotDrive41->SetSensitivity(0.5);
        driveSubRobotDrive41->SetMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
